config/routes.rb
Rails.application.routes.draw do
    resources :concerts
    get "/" => "concerts#home"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs to :concert
	validates :userid, presence:true, numericality: true
	validates :concertid, presence:true, numericality:true
	validates :comments, presence:true
	
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :comments
	validates :name, presence:true 
	validates :date, presence:true 
	validates :artist, presence:true
	validates :venue, presence:true 
	validates :city, presence:true 
	validates :ticketprice, presence:true, numericality:true 
	validates :description, presence:true  
	def self.concerts_for(date)
		Concert.where(date: date.beginning_of_month..date.end_of_month)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		 @comments = @concert.comments[:concertid]
	end
	def show
	end
	def destroy
		@concert = Concert.find params[:concertid]
		@comment = @concert.comments.find(params[:id])
		@comment.destroy
		redirect_to action: "index", controller: "concerts", project_id: @concert.id
	end
	
	def update 
		@concert = Concert.find params[:concertid]
		@comment = @concert.comments.find(params[:id])
		if @comment.update_attributes(comment_params)
			redirect_to action: "index", controller: "concerts", project_id: @concert.id
		else
			render 'edit'
		end
	end
	def edit
		@concert = Concert.find params[:concertid]
		 @comment= @concert.comments.find params[:id]
	end

	def new
		@concert = Concert.find params[:concertid]
		 @comment= @concert.comments.new
	end

	def create
		@concert =Concert.find params[:concertid]
		@comment = @concert.comments.new(comment_params)
		if @comment.save
			redirect_to action: "index", controller: "concerts", concertid: @concert.id
		else
			render 'new'
		end
	end
	private 
	def comment_params
		params.require(:comment).permit(:comments)
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	def index
		@concerts = Concert.all
		if @concerts.empty?
			render "no_concerts_found"
		end
	end

	def home
		today = Date.today
		@concerts = Concert.where("date = ?", today)
		@monthsconcerts = Concert.concerts_for(today)
	end

	def show
		unless @concert = Concert.find_by(id: params[:id])
			render 'no_concerts_found'
		end
	end
	def new
		@concert = Concert.new
	end

	def edit 
		@concert = Concert.find params[:id]
	end

	def create 
		@concert = Concert.new(concert_params)
		if @concert.save
			redirect_to action: "index", controller: "concerts"
		else
			render "new"
		end
	end

	def update
		@concert = Concert.find params[:id]
		if @concert.update_attributes(concert_params)
			redirect_to action: "index", controller: "concerts"
		else
			render "edit"
		end
	end

	def destroy 
		@concert = Concert.find(params[:id])
		@concert.destroy
		redirect_to action: "index", controller: "entries"
	end

	private

	def concert_params
		params.require(:concert).permit(:name, :date, :artist, :venue, :city, :ticketprice, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concert_helper.rb
module ConcertHelper
end

app/views/concerts/_form.html.erb
<%= form_for @concert do |f| %>
	<ul>
		<li>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</li>
		<br>
		<li>
			<%= f.label :date %>
			<%= f.date_field :date %>
		</li>
		<br>
		<li>
			<%= f.label :artist %>
			<%= f.text_field :artist %>
		</li>
		<br>
		<li>
			<%= f.label :venue %>
			<%= f.text_field :venue %>
		</li>
		<br>
		<li>
			<%= f.label :city %>
			<%= f.text_field :city %>
		</li>
		<br>
		<li>
			<%= f.label :ticketprice %>
			<%= f.text_field :ticketprice %>
		</li>
		<br>
		<li>
			<%= f.label :description %>
			<%= f.text_field :description %>
		</li>
		<br>
		<%= f.submit "Save" %>
		<%= link_to("Home", concerts_path) %>
		<%= link_to("Cancel", concerts_path) %>
<% end %>

app/views/concerts/edit.html.erb
<h2> Edit concert <%= @concert.name %> </h2>

<%= render "form" %>

app/views/concerts/home.html.erb
<div class="homecontainer container-fluid">
	<div class="bannerrow row">
	<%= image_tag "rockbanner.jpg", height: 300, width: 1500 %>
	</div>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><%= image_tag "miclogo.jpg", height: 25, width: 30 %> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to("Index", concerts_path)%> <span class="sr-only">(current)</span></li>
        <li><%= link_to("New event", new_concert_path) %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Concerts today<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><% @concerts.each do |concert| %>
					<%= link_to(concert.name, concert_path(concert)) %>
				<br>
			<% end %>
			</li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contact<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Email</a></li>
            <li>Phone</li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div class="hometoprow row">
		<div class="sidebar col-sm-4">			
			<h3>Concerts this month</h3>
			<div class="concerts">
				<% @monthsconcerts.each do |concert| %>
					<%= link_to(concert.name, concert_path(concert)) %>
						<br>
				<% end %>
			</div>
		</div>
		<div class="heading col-sm-4">
		</div>
		<div class="concertstoday col-sm-4 ">
			<h3> Top Concerts </h3>
		</div>
	</div>


</div>

app/views/concerts/index.html.erb
<ul>
	<% @concerts.each do |concert| %>
		<br>
		<li><%= link_to(concert.name, concert_path(concert)) %>
		<br>
		<%= concert.date.strftime("%m/%d/%Y")  %>
		<%= concert.artist %>
		<br>
		<%= concert.venue %>
		<%= concert.city %> 
		<br>
		<%= concert.ticketprice %>
		<br>
		<%= concert.description %></li>
		<%= link_to("Edit", edit_concert_path(concert)) %>
		<%= link_to("Delete", concert_path(concert), method: :delete, data: { confirm: "Are you sure?" }) %>
		<br>
	<% end %>

<%= link_to("Home", "/") %>

app/views/concerts/new.html.erb
<h2>Creating a new concert </h2>

<%= render "form" %>

app/views/concerts/show.html.erb
<div class="printconcerts container">
	<h1><%= "Concert Number: #{params[:id]}" %></h1>
	
	<b><%= @concert.name %></b>
		<br>
		<%= @concert.date.strftime("%m/%d/%Y")  %>
		<%= @concert.artist %>
		<br>
		<%= @concert.venue %>
		<%= @concert.city %> 
		<br>
		<%= "$#{@concert.ticketprice}" %>
		<br>
		<%= @concert.description %></li>
		<br>
	<%= link_to("Home", concerts_path) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<div class="container-fluid">
  <title>ConcertApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
	<%= yield %>	
	<div class="push"></div>
	<div class="footer"> 
	Copyright Josh Alexy 2015
</div>
</div>


</div>

</body>

</html>